[package]
name = "xapian-rusty-test"
version = "0.1.0"
authors = ["steve <ssosik@akamai.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
xapian-rusty = { path = "xapian-rusty" }
